40: Added .name to author entry to get name to display.
cqframework/sample-content-ig pull request #55
Opened 2024-01-23 17:02 UTC by echicoine-icf

https://github.com/cqframework/sample-content-ig/issues/40

2024-01-23 19:59 UTC, echicoine-icf commented
![image](https://github.com/cqframework/sample-content-ig/assets/81327339/cd87fdfe-3fb1-46ba-8a1a-19b73586993f)

2024-01-24 19:48 UTC, brynrhodes requested changes

2024-01-24 19:48 UTC, brynrhodes commented on templates/liquid/Measure.liquid
>          {% if Measure.author.exists() %}
If we're changing what we're displaying, we should also change what we're conditioning the display on, this should probably now be Measure.author.name.exists() yes?

2024-01-24 19:48 UTC, brynrhodes commented on templates/liquid/Measure.liquid
This looks good for Measure.author, but we should treat all of the ContactDetail-valued elements the same way then, update the templates for Measure.editor, Measure.reviewer, and Measure.endorser to follow suit

2024-01-24 19:48 UTC, brynrhodes commented on templates/liquid/Measure.liquid
Also note that these same elements appear in the other templates (Library, PlanDefinition, and ActivityDefinition) we should update those to be consistent as well

2024-01-25 15:38 UTC, brynrhodes approved these changes

2024-01-25 15:38 UTC, merged