Resubmitting the PR
cqframework/sample-content-ig pull request #81
Opened 2024-05-29 21:09 UTC by tanvishah9696

Reverts cqframework/sample-content-ig#80

2024-06-07 20:06 UTC, brynrhodes requested changes

2024-06-07 20:06 UTC, brynrhodes commented on _gencontinuous.sh
Still not sure why this is cleared out?

2024-06-07 20:06 UTC, brynrhodes commented on input/cql/QICoreCommonExample.cql
> +codesystem "USCoreObservationCategoryExtensionCodes": 'http://terminology.hl7.org/CodeSystem/observation-category'
This isn't right, this is specifically pointing to the USCoreObservationCategoryCodes, needs to keep the fhir/us/core CodeSystem reference

2024-06-07 20:06 UTC, brynrhodes commented on input/ignoreWarnings.txt
> -# (And include comments like this justifying why)
Need to keep these instructional messages, this is a template IG that is supposed to provide documentation on how to build a content IG, this is an important part of that

2024-06-07 20:06 UTC, brynrhodes commented on input/mycontentig.xml
> +  <url value="http://hl7.org/fhir/uv/mycontentig/ImplementationGuide/example.fhir.uv.mycontentig"/>
Don't change the URL here, this isn't an HL7 IG, it's a sample content IG, the "somewhere.org" URL is important, it's providing an example for what people should do

2024-06-07 20:06 UTC, brynrhodes commented on input/mycontentig.xml
> +  </extension>
Don't add this extension here, this isn't a CQI WG IG

2024-06-07 20:06 UTC, brynrhodes commented on input/mycontentig.xml
> +  <publisher value="HL7 International / Clinical Quality Information"/>
Don't change this value, this is example content illustrating what people should do

2024-06-07 20:06 UTC, brynrhodes commented on input/mycontentig.xml
> +      <value value="http://www.hl7.org/Special/committees/cqi"/>
Don't change this value, this is an example IG

2024-06-07 20:06 UTC, brynrhodes commented on input/resources/measure/Measure-HIVViralSuppressionFHIRExample.json
> +  "url": "http://hl7.org/fhir/uv/mycontentig/Measure/HIVViralSuppressionFHIR",
Don't change the URL here

2024-06-07 20:06 UTC, brynrhodes commented on input/resources/measure/Measure-QuestionnaireMeasureExample.json
> +  "library": [ "http://hl7.org/fhir/uv/mycontentig/Library/QuestionnaireMeasure" ],
Don't change the URL here

2024-06-07 20:06 UTC, brynrhodes commented on input/resources/measure/Measure-QuestionnaireMeasureExample.json
> +  "url": "http://hl7.org/fhir/uv/mycontentig/Measure/QuestionnaireMeasure",
Don't change the URL here

2024-06-10 16:06 UTC, jbyrdevans commented on _gencontinuous.sh
@brynrhodes - I think we saw this with Sara's PR as well. Not sure if this is just a weird GitHub comparison artifact when PR-ing from a fork? When I click View File under the ellipsis, here's what I see as the file contents:

```
#!/bin/bash
./_genonce.sh -watch
```

2025-08-26 02:33 UTC, brynrhodes commented
Overcome by events

2025-08-26 02:33 UTC, closed without merging